# Generated by Django 2.1.5 on 2019-02-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0002_auto_20190206_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PROCESSING', 'processing'), ('REJECTED', 'rejected'), ('CONFIRMED', 'confirmed'), ('DONE', 'done')], max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('callback', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=255)),
                ('user_surname', models.CharField(max_length=255)),
                ('user_middle_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.PaymentType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='shipping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.ShippingType'),
        ),
    ]
