# Generated by Django 2.1.5 on 2019-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0003_auto_20190208_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('PROCESSING', 'processing'), ('REJECTED', 'rejected'), ('CONFIRMED', 'confirmed'), ('DONE', 'done')], default='NEW', max_length=255),
        ),
    ]
